-- ID            int64     `json:"id" db:"id"`
-- Street        string    `json:"street" db:"street"`
-- Status        string    `json:"status" db:"status"`
-- Price         int       `json:"price" db:"price"`
-- Bedrooms      int       `json:"bedrooms" db:"bedrooms"`
-- Bathrooms     int       `json:"bathrooms" db:"bathrooms"`
-- SquareFootage int       `json:"sq_ft" db:"sq_ft"`
-- Latitude      float64   `json:"latitude" db:"lat"`
-- Longitude     float64   `json:"longitude" db:"lng"`

CREATE SCHEMA IF NOT EXISTS features;

CREATE TABLE IF NOT EXISTS features.listings -- naming is hard, just didn't want schema and table the same
(
    id         serial PRIMARY KEY,   -- autogenerated id
    street     text        not null, -- likely a foreign key, but not part of prompt
    status     text        not null, -- likely a foreign key, but not part of prompt
    price      integer,
    bedrooms   integer,
    bathrooms  integer,
    sq_ft      integer,
    lat        decimal,
    lng        decimal,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

ALTER SEQUENCE features.listings_id_seq RESTART WITH 2000; -- start at 2000 since we are pre-loading data
